"""init schema

Revision ID: 62a605128921
Revises: 
Create Date: 2025-08-28 19:20:30.110786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a605128921'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('target_audience', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'accepted', 'rejected', name='suggestionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_suggestions_id'), 'event_suggestions', ['id'], unique=False)
    op.drop_column('team_members', 'interests')
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.add_column('team_members', sa.Column('interests', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_event_suggestions_id'), table_name='event_suggestions')
    op.drop_table('event_suggestions')
    # ### end Alembic commands ###
